name: docker store checker CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Check format and do linting
    runs-on: ubuntu-latest
    container:
      image:
        golangci/golangci-lint:latest-alpine
    steps:
      - uses: actions/checkout@v2
      - name: check
        run: |
          golangci-lint run --timeout 1m
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: make test
